[package]
name = "compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
primitives = { path = "../../primitives" }
bindgen-macro = { path = "../../bindgen-macro" }
